### PR TITLE
Glue support

### PR DESCRIPTION
**Pull request by erowan**

### CODE REVIEW

**Comment by wild-endeavor** [comment]
looked through this for a bit, though I'm afraid I'm limited by a lack of understanding around the datahub data models/apis.  A few higher-level points though...
* Is this repo meant to be consumed as a pypi library in the future?  If so, I think we should rename the top level folder to something more unique.  `lineage` as a word is too broad, some other library might try to use it, and then if someone writes `import lineage` there can be a conflict.
* Since this work was started here, we released the next generation of dataframe support in flytekit version v0.30.0.  See the main [PR here](https://github.com/flyteorg/flytekit/pull/785), and the issue [here](https://github.com/flyteorg/flyte/issues/2074).  There's also a [cookbook document](https://docs.flyte.org/projects/cookbook/en/latest/auto/core/type_system/structured_dataset.html#sphx-glr-auto-core-type-system-structured-dataset-py) and a whole bunch of short examples in the [unit tests](https://github.com/flyteorg/flytekit/blob/master/tests/flytekit/unit/types/structured_dataset/test_structured_dataset_workflow.py). We covered this new type in a recent Flyte open-source meeting as well.
* Keep in mind that that feature is gated because you'll need to be on the 0.19.2 release of flyte (because we had to make a change to flyte propeller and flyte admin).  To enable it, make sure you have the `FLYTE_SDK_USE_STRUCTURED_DATASET=TRUE` environment variable set everywhere (in images and whenever invoking python).
* I mention the new type because one of the reasons we made that new type was to improve extensibility.  For example, we added this to the [fsspec plugin](https://github.com/flyteorg/flytekit/pull/849/files#diff-df4bdf04f2d47282f454a8164aa7c50df4a9c63c02f90ff2cf3049692f8067deR35) recently.  This interface gives complete control of how to serialize/deserialize dataframes at task run-time.  This means that you could potentially write an AWS Glue StructuredDataset encoder that will write the dataframe's parquet file to S3 and additionally register with AWS Glue at the same time.  Just food for thought.
* If we'd like to widen adoption of this codebase beyond the current use case, I think it'd be nice to have typing/type hinting in the function/class signatures.

Btw, @erowan I gave you write access to this repo so feel free to open up PRs on this repo instead of forking, merge PRs, etc.

**Comment by erowan** [comment]
> looked through this for a bit, though I'm afraid I'm limited by a lack of understanding around the datahub data models/apis. A few higher-level points though...
> 
> * Is this repo meant to be consumed as a pypi library in the future?  If so, I think we should rename the top level folder to something more unique.  `lineage` as a word is too broad, some other library might try to use it, and then if someone writes `import lineage` there can be a conflict.

I think its usage at this stage would be just within this app but I agree lineage would be a contested name. How about flylineage or flytelineage for the module?

> * Since this work was started here, we released the next generation of dataframe support in flytekit version v0.30.0.  See the main [PR here](https://github.com/flyteorg/flytekit/pull/785), and the issue [here](https://github.com/flyteorg/flyte/issues/2074).  There's also a [cookbook document](https://docs.flyte.org/projects/cookbook/en/latest/auto/core/type_system/structured_dataset.html#sphx-glr-auto-core-type-system-structured-dataset-py) and a whole bunch of short examples in the [unit tests](https://github.com/flyteorg/flytekit/blob/master/tests/flytekit/unit/types/structured_dataset/test_structured_dataset_workflow.py). We covered this new type in a recent Flyte open-source meeting as well.

I'll take a look at the new structured dataset type. 
> * Keep in mind that that feature is gated because you'll need to be on the 0.19.2 release of flyte (because we had to make a change to flyte propeller and flyte admin).  To enable it, make sure you have the `FLYTE_SDK_USE_STRUCTURED_DATASET=TRUE` environment variable set everywhere (in images and whenever invoking python).
> * I mention the new type because one of the reasons we made that new type was to improve extensibility.  For example, we added this to the [fsspec plugin](https://github.com/flyteorg/flytekit/pull/849/files#diff-df4bdf04f2d47282f454a8164aa7c50df4a9c63c02f90ff2cf3049692f8067deR35) recently.  This interface gives complete control of how to serialize/deserialize dataframes at task run-time.  This means that you could potentially write an AWS Glue StructuredDataset encoder that will write the dataframe's parquet file to S3 and additionally register with AWS Glue at the same time.  Just food for thought.

I would prefer to not embed the lineage in the client having it outside in the events has several advantages, de-coupled, client agnostic etc.

> * If we'd like to widen adoption of this codebase beyond the current use case, I think it'd be nice to have typing/type hinting in the function/class signatures.

Ah to type hint or not? It certainly should be one or the other and currently its a bit of a mix. I would prefer not to use them and document the signatures which has not been done but If your company uses type hints I can add them.

> 
> Btw, @erowan I gave you write access to this repo so feel free to open up PRs on this repo instead of forking, merge PRs, etc.

Thanks but my company mandates a forking workflow for open source contributions.

**Comment by wild-endeavor** [comment]
@erowan feel free to merge this when you feel comfortable with it.  `flytelineage` is good by me.  Thank you.

**Comment by erowan** [comment]
@wild-endeavor can you merge I don't appear to have write access.

**Pull request merged**
